package com.riease.gamer.mhw.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlchemyRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(Integer value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(Integer value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(Integer value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(Integer value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(Integer value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<Integer> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<Integer> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(Integer value1, Integer value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(Integer value1, Integer value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andJewel1IsNull() {
            addCriterion("jewel_1 is null");
            return (Criteria) this;
        }

        public Criteria andJewel1IsNotNull() {
            addCriterion("jewel_1 is not null");
            return (Criteria) this;
        }

        public Criteria andJewel1EqualTo(String value) {
            addCriterion("jewel_1 =", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1NotEqualTo(String value) {
            addCriterion("jewel_1 <>", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1GreaterThan(String value) {
            addCriterion("jewel_1 >", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1GreaterThanOrEqualTo(String value) {
            addCriterion("jewel_1 >=", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1LessThan(String value) {
            addCriterion("jewel_1 <", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1LessThanOrEqualTo(String value) {
            addCriterion("jewel_1 <=", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1Like(String value) {
            addCriterion("jewel_1 like", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1NotLike(String value) {
            addCriterion("jewel_1 not like", value, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1In(List<String> values) {
            addCriterion("jewel_1 in", values, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1NotIn(List<String> values) {
            addCriterion("jewel_1 not in", values, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1Between(String value1, String value2) {
            addCriterion("jewel_1 between", value1, value2, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel1NotBetween(String value1, String value2) {
            addCriterion("jewel_1 not between", value1, value2, "jewel1");
            return (Criteria) this;
        }

        public Criteria andJewel2IsNull() {
            addCriterion("jewel_2 is null");
            return (Criteria) this;
        }

        public Criteria andJewel2IsNotNull() {
            addCriterion("jewel_2 is not null");
            return (Criteria) this;
        }

        public Criteria andJewel2EqualTo(String value) {
            addCriterion("jewel_2 =", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2NotEqualTo(String value) {
            addCriterion("jewel_2 <>", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2GreaterThan(String value) {
            addCriterion("jewel_2 >", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2GreaterThanOrEqualTo(String value) {
            addCriterion("jewel_2 >=", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2LessThan(String value) {
            addCriterion("jewel_2 <", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2LessThanOrEqualTo(String value) {
            addCriterion("jewel_2 <=", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2Like(String value) {
            addCriterion("jewel_2 like", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2NotLike(String value) {
            addCriterion("jewel_2 not like", value, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2In(List<String> values) {
            addCriterion("jewel_2 in", values, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2NotIn(List<String> values) {
            addCriterion("jewel_2 not in", values, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2Between(String value1, String value2) {
            addCriterion("jewel_2 between", value1, value2, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel2NotBetween(String value1, String value2) {
            addCriterion("jewel_2 not between", value1, value2, "jewel2");
            return (Criteria) this;
        }

        public Criteria andJewel3IsNull() {
            addCriterion("jewel_3 is null");
            return (Criteria) this;
        }

        public Criteria andJewel3IsNotNull() {
            addCriterion("jewel_3 is not null");
            return (Criteria) this;
        }

        public Criteria andJewel3EqualTo(String value) {
            addCriterion("jewel_3 =", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3NotEqualTo(String value) {
            addCriterion("jewel_3 <>", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3GreaterThan(String value) {
            addCriterion("jewel_3 >", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3GreaterThanOrEqualTo(String value) {
            addCriterion("jewel_3 >=", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3LessThan(String value) {
            addCriterion("jewel_3 <", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3LessThanOrEqualTo(String value) {
            addCriterion("jewel_3 <=", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3Like(String value) {
            addCriterion("jewel_3 like", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3NotLike(String value) {
            addCriterion("jewel_3 not like", value, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3In(List<String> values) {
            addCriterion("jewel_3 in", values, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3NotIn(List<String> values) {
            addCriterion("jewel_3 not in", values, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3Between(String value1, String value2) {
            addCriterion("jewel_3 between", value1, value2, "jewel3");
            return (Criteria) this;
        }

        public Criteria andJewel3NotBetween(String value1, String value2) {
            addCriterion("jewel_3 not between", value1, value2, "jewel3");
            return (Criteria) this;
        }

        public Criteria andTargetIndexIsNull() {
            addCriterion("target_index is null");
            return (Criteria) this;
        }

        public Criteria andTargetIndexIsNotNull() {
            addCriterion("target_index is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIndexEqualTo(String value) {
            addCriterion("target_index =", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexNotEqualTo(String value) {
            addCriterion("target_index <>", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexGreaterThan(String value) {
            addCriterion("target_index >", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexGreaterThanOrEqualTo(String value) {
            addCriterion("target_index >=", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexLessThan(String value) {
            addCriterion("target_index <", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexLessThanOrEqualTo(String value) {
            addCriterion("target_index <=", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexLike(String value) {
            addCriterion("target_index like", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexNotLike(String value) {
            addCriterion("target_index not like", value, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexIn(List<String> values) {
            addCriterion("target_index in", values, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexNotIn(List<String> values) {
            addCriterion("target_index not in", values, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexBetween(String value1, String value2) {
            addCriterion("target_index between", value1, value2, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andTargetIndexNotBetween(String value1, String value2) {
            addCriterion("target_index not between", value1, value2, "targetIndex");
            return (Criteria) this;
        }

        public Criteria andIsUsedIsNull() {
            addCriterion("is_used is null");
            return (Criteria) this;
        }

        public Criteria andIsUsedIsNotNull() {
            addCriterion("is_used is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsedEqualTo(Boolean value) {
            addCriterion("is_used =", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotEqualTo(Boolean value) {
            addCriterion("is_used <>", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedGreaterThan(Boolean value) {
            addCriterion("is_used >", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_used >=", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedLessThan(Boolean value) {
            addCriterion("is_used <", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_used <=", value, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedIn(List<Boolean> values) {
            addCriterion("is_used in", values, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotIn(List<Boolean> values) {
            addCriterion("is_used not in", values, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_used between", value1, value2, "isUsed");
            return (Criteria) this;
        }

        public Criteria andIsUsedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_used not between", value1, value2, "isUsed");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUsedTypeIsNull() {
            addCriterion("used_type is null");
            return (Criteria) this;
        }

        public Criteria andUsedTypeIsNotNull() {
            addCriterion("used_type is not null");
            return (Criteria) this;
        }

        public Criteria andUsedTypeEqualTo(String value) {
            addCriterion("used_type =", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeNotEqualTo(String value) {
            addCriterion("used_type <>", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeGreaterThan(String value) {
            addCriterion("used_type >", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("used_type >=", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeLessThan(String value) {
            addCriterion("used_type <", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeLessThanOrEqualTo(String value) {
            addCriterion("used_type <=", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeLike(String value) {
            addCriterion("used_type like", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeNotLike(String value) {
            addCriterion("used_type not like", value, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeIn(List<String> values) {
            addCriterion("used_type in", values, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeNotIn(List<String> values) {
            addCriterion("used_type not in", values, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeBetween(String value1, String value2) {
            addCriterion("used_type between", value1, value2, "usedType");
            return (Criteria) this;
        }

        public Criteria andUsedTypeNotBetween(String value1, String value2) {
            addCriterion("used_type not between", value1, value2, "usedType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alchemy_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}