package com.riease.gamer.mhw.entity;

import com.riease.gamer.mhw.model.Entity;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table alchemy_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AlchemyRecord extends Entity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.sn
     *
     * @mbg.generated
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.jewel_1
     *
     * @mbg.generated
     */
    private String jewel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.jewel_2
     *
     * @mbg.generated
     */
    private String jewel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.jewel_3
     *
     * @mbg.generated
     */
    private String jewel3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.target_index
     *
     * @mbg.generated
     */
    private String targetIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.is_used
     *
     * @mbg.generated
     */
    private Boolean isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alchemy_record.used_type
     *
     * @mbg.generated
     */
    private String usedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.uid
     *
     * @return the value of alchemy_record.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.uid
     *
     * @param uid the value for alchemy_record.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.sn
     *
     * @return the value of alchemy_record.sn
     *
     * @mbg.generated
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withSn(Integer sn) {
        this.setSn(sn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.sn
     *
     * @param sn the value for alchemy_record.sn
     *
     * @mbg.generated
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.jewel_1
     *
     * @return the value of alchemy_record.jewel_1
     *
     * @mbg.generated
     */
    public String getJewel1() {
        return jewel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withJewel1(String jewel1) {
        this.setJewel1(jewel1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.jewel_1
     *
     * @param jewel1 the value for alchemy_record.jewel_1
     *
     * @mbg.generated
     */
    public void setJewel1(String jewel1) {
        this.jewel1 = jewel1 == null ? null : jewel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.jewel_2
     *
     * @return the value of alchemy_record.jewel_2
     *
     * @mbg.generated
     */
    public String getJewel2() {
        return jewel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withJewel2(String jewel2) {
        this.setJewel2(jewel2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.jewel_2
     *
     * @param jewel2 the value for alchemy_record.jewel_2
     *
     * @mbg.generated
     */
    public void setJewel2(String jewel2) {
        this.jewel2 = jewel2 == null ? null : jewel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.jewel_3
     *
     * @return the value of alchemy_record.jewel_3
     *
     * @mbg.generated
     */
    public String getJewel3() {
        return jewel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withJewel3(String jewel3) {
        this.setJewel3(jewel3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.jewel_3
     *
     * @param jewel3 the value for alchemy_record.jewel_3
     *
     * @mbg.generated
     */
    public void setJewel3(String jewel3) {
        this.jewel3 = jewel3 == null ? null : jewel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.target_index
     *
     * @return the value of alchemy_record.target_index
     *
     * @mbg.generated
     */
    public String getTargetIndex() {
        return targetIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withTargetIndex(String targetIndex) {
        this.setTargetIndex(targetIndex);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.target_index
     *
     * @param targetIndex the value for alchemy_record.target_index
     *
     * @mbg.generated
     */
    public void setTargetIndex(String targetIndex) {
        this.targetIndex = targetIndex == null ? null : targetIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.is_used
     *
     * @return the value of alchemy_record.is_used
     *
     * @mbg.generated
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withIsUsed(Boolean isUsed) {
        this.setIsUsed(isUsed);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.is_used
     *
     * @param isUsed the value for alchemy_record.is_used
     *
     * @mbg.generated
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.create_time
     *
     * @return the value of alchemy_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.create_time
     *
     * @param createTime the value for alchemy_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alchemy_record.used_type
     *
     * @return the value of alchemy_record.used_type
     *
     * @mbg.generated
     */
    public String getUsedType() {
        return usedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    public AlchemyRecord withUsedType(String usedType) {
        this.setUsedType(usedType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alchemy_record.used_type
     *
     * @param usedType the value for alchemy_record.used_type
     *
     * @mbg.generated
     */
    public void setUsedType(String usedType) {
        this.usedType = usedType == null ? null : usedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", sn=").append(sn);
        sb.append(", jewel1=").append(jewel1);
        sb.append(", jewel2=").append(jewel2);
        sb.append(", jewel3=").append(jewel3);
        sb.append(", targetIndex=").append(targetIndex);
        sb.append(", isUsed=").append(isUsed);
        sb.append(", createTime=").append(createTime);
        sb.append(", usedType=").append(usedType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}