package com.riease.gamer.mhw.entity;

import com.riease.gamer.mhw.model.Entity;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jewel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Jewel extends Entity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jewel.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jewel.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jewel.rare
     *
     * @mbg.generated
     */
    private Integer rare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jewel.socket
     *
     * @mbg.generated
     */
    private Integer socket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jewel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jewel.uid
     *
     * @return the value of jewel.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    public Jewel withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jewel.uid
     *
     * @param uid the value for jewel.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jewel.name
     *
     * @return the value of jewel.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    public Jewel withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jewel.name
     *
     * @param name the value for jewel.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jewel.rare
     *
     * @return the value of jewel.rare
     *
     * @mbg.generated
     */
    public Integer getRare() {
        return rare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    public Jewel withRare(Integer rare) {
        this.setRare(rare);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jewel.rare
     *
     * @param rare the value for jewel.rare
     *
     * @mbg.generated
     */
    public void setRare(Integer rare) {
        this.rare = rare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jewel.socket
     *
     * @return the value of jewel.socket
     *
     * @mbg.generated
     */
    public Integer getSocket() {
        return socket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    public Jewel withSocket(Integer socket) {
        this.setSocket(socket);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jewel.socket
     *
     * @param socket the value for jewel.socket
     *
     * @mbg.generated
     */
    public void setSocket(Integer socket) {
        this.socket = socket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", name=").append(name);
        sb.append(", rare=").append(rare);
        sb.append(", socket=").append(socket);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}