package com.riease.gamer.mhw.mapper;

import com.riease.gamer.mhw.entity.AlchemyRecord;
import com.riease.gamer.mhw.entity.AlchemyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AlchemyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    long countByExample(AlchemyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int deleteByExample(AlchemyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int insert(AlchemyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int insertSelective(AlchemyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    List<AlchemyRecord> selectByExampleWithRowbounds(AlchemyRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    List<AlchemyRecord> selectByExample(AlchemyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    AlchemyRecord selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlchemyRecord record, @Param("example") AlchemyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlchemyRecord record, @Param("example") AlchemyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlchemyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alchemy_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlchemyRecord record);
}