package com.riease.gamer.mhw.mapper;

import com.riease.gamer.mhw.entity.Jewel;
import com.riease.gamer.mhw.entity.JewelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JewelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    long countByExample(JewelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int deleteByExample(JewelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int insert(Jewel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int insertSelective(Jewel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    List<Jewel> selectByExampleWithRowbounds(JewelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    List<Jewel> selectByExample(JewelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    Jewel selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Jewel record, @Param("example") JewelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Jewel record, @Param("example") JewelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jewel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jewel record);
}